### ISSUE TITLE
[iOS] Clearing cache delete IPTV and vox as well.

### ISSUE THREAD

**Issue by Manukineko** [omega-gg/MotionMonkey-dev#2]
As the title says.
1. Go to Settings > Application > Clear Cache
2. Tap Yes

When you want to do a research, IPTV and vox aren't available anymore.

There is no way to have them back without deleting the app and reinstall it.

It might be a feature to avoid copyrighted infringment (as the screenshots on the appstore don't show any of those two services, either.) and have MotionMonkey approved by Apple.

**Comment by 3unjee** [comment]
Thank you for this. I'm currently pushing a new version. We'll see if it fixes your issue.

**Comment by 3unjee** [comment]
@Manukineko The latest version shouldn't behave like, can you test on your side and let me know ?
