### ISSUE TITLE
Provide a built-in `Keep window on top` feature

### ISSUE THREAD

**Issue by GleammerRay** [omega-gg/MotionMonkey-dev#3]
Hello!

First of all, great job on your projects, really enjoying them so far. One thing I must note thought is that I haven't found any built-in feature to `Keep window on top`. I am aware that I can use my desktop manager to configure, but it takes some time to make that change permanent and it is something I'd be expecting from a video player such as this one, as it feels and works a lot like a video popout.

I'd prioritize this feature for Windows first, as although it would be nice to see it on Linux, most Linux desktop environments provide a way for this to be configured by default when Windows doesn't.

I hope that you're having a good day!

**Comment by 3unjee** [comment]
Greetings @GleammerRay, this option actually exists in Settings > Advanced > Stay on top.

You have to click the cog, then the "Player" dropdown to access these settings.
